/// Firebase Configuration File
/// This file is auto-generated by flutterfire CLI
/// To regenerate: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase options for use when the current Firebase project config
/// cannot be auto-detected. Generated by flutterfire configure.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    }
    if (defaultTargetPlatform == TargetPlatform.linux) {
      return linux;
    }
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions has not been configured for ${defaultTargetPlatform.name}.',
    );
  }

  /// Android Firebase Configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs7SpQrN-ges-4aG2GaBWltgqU2jaVYnI',
    appId: '1:419245381792:android:93341cc793fcbbb23291c5',
    messagingSenderId: '419245381792',
    projectId: 'bias-mitra-v1',
    storageBucket: 'bias-mitra-v1.firebasestorage.app',
  );

  /// TODO: Replace with your Firebase Android config from Firebase Console

  /// iOS Firebase Configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYeJ2Dm28Q7dvsndj8EK1K5wLc3_U-mKg',
    appId: '1:419245381792:ios:75d933ed762dad413291c5',
    messagingSenderId: '419245381792',
    projectId: 'bias-mitra-v1',
    storageBucket: 'bias-mitra-v1.firebasestorage.app',
    iosClientId: '419245381792-7t9atgja9uj096l22fl52m42fg57fm33.apps.googleusercontent.com',
    iosBundleId: 'com.example.biasMitra',
  );

  /// TODO: Replace with your Firebase iOS config from Firebase Console

  /// Web Firebase Configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3iFS5aO40QAH0ezDgrpbWE7XGVsa6amk',
    appId: '1:419245381792:web:0c89a506b8b4e3753291c5',
    messagingSenderId: '419245381792',
    projectId: 'bias-mitra-v1',
    authDomain: 'bias-mitra-v1.firebaseapp.com',
    storageBucket: 'bias-mitra-v1.firebasestorage.app',
  );

  /// TODO: Replace with your Firebase Web config from Firebase Console

  /// Windows Firebase Configuration

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3iFS5aO40QAH0ezDgrpbWE7XGVsa6amk',
    appId: '1:419245381792:web:aeed121a9937025b3291c5',
    messagingSenderId: '419245381792',
    projectId: 'bias-mitra-v1',
    authDomain: 'bias-mitra-v1.firebaseapp.com',
    storageBucket: 'bias-mitra-v1.firebasestorage.app',
  );

  /// TODO: Replace with your Firebase Windows config from Firebase Console

  /// macOS Firebase Configuration

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYeJ2Dm28Q7dvsndj8EK1K5wLc3_U-mKg',
    appId: '1:419245381792:ios:75d933ed762dad413291c5',
    messagingSenderId: '419245381792',
    projectId: 'bias-mitra-v1',
    storageBucket: 'bias-mitra-v1.firebasestorage.app',
    iosClientId: '419245381792-7t9atgja9uj096l22fl52m42fg57fm33.apps.googleusercontent.com',
    iosBundleId: 'com.example.biasMitra',
  );

  /// TODO: Replace with your Firebase macOS config from Firebase Console

  /// Linux Firebase Configuration
  /// TODO: Replace with your Firebase Linux config from Firebase Console
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'bias-mitra-solution-challenge',
    databaseURL: 'https://bias-mitra-solution-challenge.firebaseio.com',
  );
}